### ISSUE TITLE
Weekly Link Set

### ISSUE THREAD

**Issue by NESOY** [WeareSoft/archive#2]
토비님 블로그
http://toby.epril.com/

**Comment by NESOY** [comment]
한국에서 자율 출퇴근 혹은 원격 근무가 되는 회사가 어디 있을까?
https://github.com/milooy/remote-or-flexible-work-company-in-korea

**Comment by NESOY** [comment]
개발자 트렌드 
http://readpost.co/
배달의민족 면접에서 듣게 되는 질문 65가지(2018년 ver.)
http://www.bloter.net/archives/322886
카카오 경력공채 면접 후기
https://encyphered.github.io/blog/note/2018/09/26/kakao-interview-review.html

**Comment by gmlwjd9405** [comment]
-추가-
1. Tech Posts 하위 Site에 개발자 트렌드 추가 (개발 관련 뉴스나 레터를 볼 수 있는 사이트는 여기 추가하면 될듯)
2. Interview Question 하위 Site에 배달의민족 면접에서 듣게 되는 질문 65가지(2018년 ver.)추가 (
3. Interview Question 하위 Review에 카카오 경력 공채 면접 후기 추가 (대신, 정확한 기간을 적어주면 좋을듯 Ex. 2018 하반기)

-보류-
1. 토비님 블로그에 최근에는 작성된 글이 없는듯하여 논의 필요
2. 한국에서 자율 출퇴근 혹은 원격 근무가 되는 회사가 어디 있을까?는 분류의 문제에 대한 논의 필요

**Comment by NESOY** [comment]
쿠팡 블로그
https://medium.com/coupang-tech

**Comment by gmlwjd9405** [comment]
-추가-
* Blog 하위 - 쿠팡 블로그 추가 

-보류-
* "Github의 장애 발생과 분석과 대처에 대한 좋은 글"는 분류의 문제에 대한 논의 필요

추가할 내용마다 하나의 Issue로 남기는 것이 좋을 것 같습니다. :)

**Comment by NESOY** [comment]
네네 ㅎㅎㅎ 해당 이슈는 닫을게요. 👍
